# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3fae81da0380708d76021da07b8830792fd7cc9994e1a4a5ad0fb6ec14ae878dcd20cfb6a9e0b733fa02267e268c203b572f620d1c95b4d0f13b9e3599d82998

test:
  secret_key_base: 264a74dd42cf6e78423f0253f0fa1a1ee309b76cfc9fa87dc59e743071e11bbf3edff270c6fb054056c585d8aa5b61056e51933f12d0d1dcd1f2be90171a8ee6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
